### ISSUE TITLE
Bug: HTML elements don't scale with screen size

### ISSUE THREAD

**Issue by NewtonLC** [cse110-sp24-group31/Dev-Journal#11]
![image](https://github.com/cse110-sp24-group31/Dev-Journal/assets/55558755/c3bca355-621d-458a-91b6-2635349af719)

**Comment by kiminus** [comment]
it will prioritize overflow before resize though, if the screen width is small enough it would resize
I think you intend to resize the container?

**Comment by kiminus** [comment]
this issue would be resolve [on this issue,](https://github.com/cse110-sp24-group31/Dev-Journal/issues/2)
